imagePullPolicy: Always

namespace: default
node:
  name: node
  image: 
    repository: charanreddy12/multi-env-app
    tag: latest
  replicaCount: 1
  
  service:
    type: ClusterIP
    port: 3000
  
  resources:
    limits:
      cpu: "250m"
      memory: "256Mi"
    requests:
      cpu: "150m"
      memory: "128Mi"

mongo:
  name: mongo
  image: 
    repository: mongo
    tag: "6.0"
  replicaCount: 1
  database: mydata

  service:
    type: ClusterIP
    port: 27017

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

Volumes:
  pvc:
    name: mongo-pvc
    size: 500Mi
    accessModes: 
      - ReadWriteOnce
    reclaimPolicy: Delete
    storageClassName: multi

storageClass:
  name: multi
  provisioner: rancher.io/local-path
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Delete

ingress:
  enabled: false
  name: multi-env-ingress
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: www.example.com
  paths:
    - /