apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CharanReddy129/multi-env-node.git'
    targetRevision: dev
    path: ./multi-env
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true