apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-stage
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/CharanReddy129/multi-env-node.git'
    targetRevision: stage
    path: ./multi-env
    helm:
      valueFiles:
        - values-stage.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true