apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongo.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.mongo.name }}-svc
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongo.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.name }}
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        ports:
        - containerPort: {{ .Values.mongo.service.port }}
        resources:
          {{- toYaml .Values.mongo.resources | nindent 10 }}
        volumeMounts:
        - name: {{ .Values.Volumes.pvc.name }}
          mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.Volumes.pvc.name }}
      spec:
        accessModes:
{{- toYaml .Values.Volumes.pvc.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.Volumes.pvc.size }}
        storageClassName: {{ .Values.Volumes.pvc.storageClassName | default "multi" }}