apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongo.name }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.mongo.name }}