name: multi-env-deployment
on: 
  # push:
  #   branches:
  #     - main
  #     - dev
  #     - stage
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - main
      image_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: multi-env-app
  IMAGE_TAG: ${{ github.event.inputs.image_tag }}-${{ github.event.inputs.branch }}

jobs:
  image-build:
    runs-on: self-hosted
    steps:
      - name: checkout-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: build-and-push
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  
  image-tag:
    needs: image-build
    runs-on: self-hosted
    steps:
      - name: checkout-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}
      
      - name: edit image tags
        run: |
          chmod +x ./scripts/edit-tag.sh
          ./scripts/edit-tag.sh
    
  deploy:
    needs: image-tag
    runs-on: self-hosted
    steps:
      - name: checkout-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}
      
      - name: deploying to k8s cluster
        run: |
          chmod +x ./scripts/deployment.sh
          ./scripts/deployment.sh