name: multi-env-deployment
on: 
  # push:
  #   branches:
  #     - main
  #     - dev
  #     - stage
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - main
      image_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/multi-env-app:${{ github.event.inputs.image_tag }}-${{  github.event.inputs.branch }}
  
  image-tag:
    needs: image-build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}
      
      - name: edit image tags
        run: |
          git config --global user.name "charan"
          git config --global user.email "charan@gmail.com"
          git switch ${{ github.event.inputs.branch }}
          if [ "${{ github.event.inputs.branch }}" == "dev" ]; then
            sed -i "s/tag: .*/tag: \"${{ github.event.inputs.image_tag }}-dev\"/g" multi-env/values-dev.yaml
          elif [ "${{ github.event.inputs.branch }}" == "stage" ]; then
            sed -i "s/tag: .*/tag: \"${{ github.event.inputs.image_tag }}-stage\"/g" multi-env/values-stage.yaml
          else
            sed -i "s/tag: .*/tag: \"${{ github.event.inputs.image_tag }}-main\"/g" multi-env/values-prod.yaml
          fi

          git add .
          
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
          git commit -m "Updated image tag to ${{ github.event.inputs.image_tag }} in ${{ github.event.inputs.branch }} branch"
          git push origin ${{ github.event.inputs.branch }}
          fi